language: objective-c
osx_image: xcode10.2

install:
  - gem install xcpretty
  - gem install cocoapods
  - pod update
  - pod install

script:
- pod lib lint
- xcodebuild clean build test -workspace Ryu.xcworkspace -scheme Ryu-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' -sdk iphonesimulator12.2 CODE_SIGNING_REQUIRED=NO -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES | xcpretty -c
- xcodebuild build test -workspace Ryu.xcworkspace -scheme Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' -sdk iphonesimulator12.2 CODE_SIGNING_REQUIRED=NO -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES | xcpretty -c
